@startuml

[*] --> Создан

Создан --> Назначен : сотрудник берет тикет
Создан --> Закрыт : админ закрывает

Назначен --> В_работе : сотрудник начинает работу
Назначен --> Закрыт : админ закрывает

В_работе --> Решён : проблема устранена
В_работе --> Назначен : переназначение

Решён --> Закрыт : дополнительных вопросов нет
Решён --> В_работе : уточнение проблемы

Закрыт --> [*]

@enduml