@startuml

[*] --> Создан

Создан --> Назначен : сотрудник берет тикет
Создан --> Закрыт : админ закрывает

Назначен --> В_работе : сотрудник начинает работу
Назначен --> Закрыт : админ закрывает

В_работе --> Решён : проблема устранена
В_работе --> Назначен : приостановка работы

Решён --> Закрыт : пользователь согласен или не отвечает
Решён --> Назначен : уточнение проблемы

Закрыт --> [*]

@enduml