@startuml
title Ticket Managment System

skinparam componentStyle rectangle
skinparam shadowing false
skinparam packageStyle rectangle

actor User
actor "Backend Client" as S2S

rectangle "Ticketing Platform" {

  rectangle "API Gateway" as Gateway

  package "Auth Context" {
    component "Auth Service\n(JWT + Sessions)" as AuthService
    database "Auth DB" as AuthDB
    component "Redis" as Redis
  }

  package "Ticket Context" {
    component "Ticket Service\n(Tickets, Comments,\nAssignment, Search)" as TicketService
    database "Ticket DB" as TicketDB
  }

  package "Notification Context" {
    component "Notification Service" as NotificationService
    database "Notification DB" as NotificationDB
  }

  queue "Kafka Cluster" as Kafka

  package "Observability" {
    component "Logstash"
    component "Prometheus"
    component "Grafana"
  }
}

User --> Gateway : HTTPS(Session)
S2S --> Gateway : HTTPS(JWT)

Gateway --> AuthService
Gateway --> TicketService

AuthService --> AuthDB
AuthService --> Redis

TicketService --> TicketDB
TicketService --> Kafka : Publish events\n(TicketCreated, StatusChanged)

Kafka --> NotificationService : Consume events
NotificationService --> NotificationDB

AuthService --> Logstash
TicketService --> Logstash
NotificationService --> Logstash

AuthService --> Prometheus
TicketService --> Prometheus
NotificationService --> Prometheus

Prometheus --> Grafana

@enduml